import type { SectionsConfig } from "@/types/section";
export const sectionsConfig: SectionsConfig = {
  hero: { enabled: true, order: 1 },
  about: {
    enabled: true,
    order: 2,
    title: "About Me",
    navLabel: "About",
    href: "/#about",
    eyebrow: "01 / About",
  },
  skills: {
    enabled: true,
    order: 3,
    title: "My Skills",
    navLabel: "Skills",
    href: "/#skills",
    eyebrow: "02 / Skills",
  },
  experience: {
    enabled: true,
    order: 4,
    title: "People I’ve designed for.",
    navLabel: "Experience",
    href: "/#experience",
    eyebrow: "03 / Experience",
  },
  portfolio: {
    enabled: true,
    order: 5,
    title: "Selected projects.",
    navLabel: "Projects",
    href: "/#portfolio",
    eyebrow: "04 / Projects",
  },
  contact: {
    enabled: true,
    order: 6,
    title: "Let’s make something meaningful.",
    navLabel: "Contact",
    href: "/#contact",
    eyebrow: "05 / Contact",
    intro: "Have a brand, event, or idea in mind? Let’s talk.",
  },
};
